language: node_js
node_js:
- '5'
branches:
  only:
  - "/^v[0-9]/"
before_script:
- npm run build
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: XCZiNL/w0WZCMSq6YLrUX1HkQurkI6hP4pv59sxiEVe2Lpe3LfuBrQA6ftez9+JZKP6AyqE1I7qLVTEaH/ct0guSNIsmIMNCShjmIffJ4JQEX9HbG3xiHF/1zLG9p2CCq8mxg8fNtTsYUfZSlEz3FVe/fI2RzU8ekBp5zYYSctiH6Rrjmgcngqi5+cqVVO//hbmZKj3izBhRR5IhH0KZJ+B0nxR44mOYKOSkz6qxVGIz3PVvqVc1lWnAxL2SN7R9XAqFu4tx1jlKdRnJoLRGt99Wr9JX3FWqN25/rRtmc5bf9aoRlghWp9JPTZJrbOKGRxj1Pv3l1/gNLvuYoOsf+MvmcjJTUx6eQfP8i/nDiczls+44jqnEvusCMToEqlwAiKwucJaxooeGzNL5sOSBxbpIdX1Iesvo4+P3jc/6+A79zngG92Rx9Ac2cGZPlnIA+XbrBjGFyfmFwOUjqWr2VZsK8pys2gnuYwVWkJV2iZuDBKnLrfKgGvl4z4EnxLAYSANFn8DxzyDuKBGTxEhzsUYNHRZdSbiW61Ls13U7AtCyVSs1TVH3c7x6+AK+x5sueVdIAOJH0ANgO00XuiRf1r5orkbpPQVDH0lu6qGkuHQ4RaI0yZmDaCcPqEMZCxthpZ0nVs+90K32Qz9nZFGa35zGjC4OlMVjwjuFXUdmocU=
  on:
    tags: true
    branches: true
